---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 742805154274017280-ThLgUUCQEYZBLhcpkIAxcp0Kvl2dWBR
:access_token_secret: aTbWfdCQnGIJJf2r7Fkz47sErwaXnraSm6YJUDW51aLeF
